### ISSUE TITLE
update modules

### ISSUE THREAD

**Issue by serapath** [serapath/workshopping#1]
## `@todo`
* [ ] rename https://github.com/wizardamigos/wizardamigos-workshop to `wizardamigos-workshopping`
* [ ] make a wizardamigos theme and add it to that module
* [ ] use it in https://github.com/wizardamigos/workshop-buy-bitcoins
* [ ] use it in https://github.com/wizardamigos/workshop_app
* [ ] use it in https://github.com/ninabreznik/workshop-js-portfolio

---
